### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by jsonmaf1a** [noti-rs/notihub#1]
# Example 1:

### Config:

```toml
[[custom]]
name = "switch_kb_layout"

[custom.module]
script = "./scripts/kb.sh"
icon = "/path/to/icon.svg"
urgency = "low"
summary = { format = "current layout: $value" }

# $value - script output
```

### Script:

```sh
# ./scripts/kb.sh
keyboard = "keyboard name"

kb switch $keyboard

return_value = # get current kb layout
echo return_value
```

### Usage:

```conf
bind = SUPER, SPACE, exec, notihub call "switch_kb_layout"
```

---

# Example 2:

### Config:

```toml
[[custom]]
name = "volume_increase"

[custom.module]
script = "./scripts/volume.sh increase"
icon = "/path/to/icon2.svg"
urgency = "low"
summary = { format = "Volume: $value" }

# ---

[[custom]]
name = "volume_decrease"

[custom.module]
script = "./scripts/volume.sh decrease"
icon = "/path/to/icon2.svg"
urgency = "low"
summary = { format = "Volume: $value" }

# ---

[[custom]]
name = "volume_toggle_mute"

[custom.module]
script = "./scripts/volume.sh toggle_mute"
replace = false

type = "toggle"
# allows you to pass tuple to some properties, where tuple.0 applies if toggle state == true, and tuple.1 if state == false, state controled by script - look examples below 

urgency = ["critical", "low"] # means critical if script returns true(volume muted) and low if script returns false(volume unmuted)
timeout = [0, "default"]
summary = { format = ["Volume muted", "Volume unmuted"]}
```

### Script:

```sh
# ./scripts/volume.sh

case $1 in
increase)
    pamixer -i 5 -u
    echo "$(pamixer --get-volume)%"
    ;;
decrease)
    pamixer -d 5 -u
    echo "$(pamixer --get-volume)%"
    ;;
toggle_mute)
    pamixer -t
    if $(pamixer --get-mute); then
        echo true
    else
        echo false
    fi
    ;;
esac
```

### Usage:

```conf
bindel = , XF86AudioRaiseVolume, exec, notihub call "volume_increase"
bindel = , XF86AudioLowerVolume, exec, notihub call "volume_decrease"
bindl = , XF86AudioMute, exec, notihub call "volume_toggle_mute"
```
